# Generated by Django 5.2.6 on 2025-09-18 22:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Empresa', max_length=200)),
                ('direccion', models.TextField(default='')),
                ('telefono', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('rnc', models.CharField(default='', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
    ]
