# Generated by Django 5.2.6 on 2025-10-20 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobantes', '0001_initial'),
        ('config', '0001_initial'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='factura_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturas.factura', verbose_name='Factura Asignada'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='config.empresa'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_comprobante', to='config.empresa'),
        ),
        migrations.AddField(
            model_name='tipocomprobante',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos_comprobante', to='config.empresa'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.tipocomprobante'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='tipo_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.tipocomprobante'),
        ),
    ]
