# Generated by Django 5.2.5 on 2025-09-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0002_rename_descricion_tipocomprobante_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='numero_comprobante_completo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
