# Generated by Django 5.2.5 on 2025-09-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0004_comprobante_factura_asignada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriecomprobante',
            name='serie',
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='desde',
            field=models.IntegerField(blank=True, null=True, verbose_name='Desde'),
        ),
        migrations.AddField(
            model_name='seriecomprobante',
            name='hasta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hasta'),
        ),
    ]
