# Generated by Django 5.2.6 on 2025-10-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0005_remove_seriecomprobante_serie_seriecomprobante_desde_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriecomprobante',
            name='anulado',
            field=models.BooleanField(default=False, verbose_name='Anulado'),
        ),
    ]
