# Generated by Django 5.2.6 on 2025-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_factura_ncf_asignado_alter_factura_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción personalizada del producto', null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción personalizada del producto', null=True),
        ),
    ]
