# Generated by Django 5.2.5 on 2025-08-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Pendiente', 'Pendiente'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20),
        ),
    ]
