# Generated by Django 5.2.5 on 2025-09-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_factura_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numero_factura',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
