# Generated by Django 5.2.5 on 2025-09-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0004_comprobante_factura_asignada_and_more'),
        ('facturas', '0003_alter_cotizacion_numero_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='ncf_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comprobantes.comprobante', verbose_name='NCF Asignado'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Pendiente', 'Pendiente'), ('Activa', 'Activa'), ('Pagada', 'Pagada'), ('Anulada', 'Anulada')], default='Pendiente', max_length=20),
        ),
    ]
