# Generated by Django 5.2.5 on 2025-08-18 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(max_length=50)),
                ('descricion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=50)),
                ('numero_actual', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_vencimiento', models.DateField()),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.tipocomprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_comprobante', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('anulado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('tipo_comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comprobantes.tipocomprobante')),
            ],
        ),
    ]
