# Generated by Django 5.2.5 on 2025-08-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocomprobante',
            old_name='descricion',
            new_name='descripcion',
        ),
    ]
