# Generated by Django 5.2.5 on 2025-09-11 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_telefono'),
        ('comprobantes', '0003_comprobante_numero_comprobante_completo'),
        ('facturas', '0003_alter_cotizacion_numero_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='factura_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturas.factura', verbose_name='Factura Asignada'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
